name: wifi_connector_example
description: Demonstrates how to use the wifi_connector plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  wifi_connector:
    path: ../

flutter:
  uses-material-design: true

